// <auto-generated />
using System;
using Jam.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jam.Api.Migrations.StoryDb
{
    [DbContext(typeof(StoryDbContext))]
    [Migration("20251203195048_InitialStoryDb")]
    partial class InitialStoryDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Jam.Api.Models.AnswerOption", b =>
                {
                    b.Property<int>("AnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionSceneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerOptionId");

                    b.HasIndex("QuestionSceneId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("Jam.Api.Models.EndingScene", b =>
                {
                    b.Property<int>("EndingSceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndingText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EndingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EndingSceneId");

                    b.HasIndex("StoryId");

                    b.ToTable("EndingScenes");
                });

            modelBuilder.Entity("Jam.Api.Models.IntroScene", b =>
                {
                    b.Property<int>("IntroSceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntroText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IntroSceneId");

                    b.HasIndex("StoryId")
                        .IsUnique();

                    b.ToTable("IntroScenes");
                });

            modelBuilder.Entity("Jam.Api.Models.PlayingSession", b =>
                {
                    b.Property<int>("PlayingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentSceneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentSceneType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayingSessionId");

                    b.HasIndex("StoryId");

                    b.ToTable("PlayingSessions");
                });

            modelBuilder.Entity("Jam.Api.Models.QuestionScene", b =>
                {
                    b.Property<int>("QuestionSceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextQuestionSceneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionSceneId");

                    b.HasIndex("NextQuestionSceneId")
                        .IsUnique();

                    b.HasIndex("StoryId");

                    b.ToTable("QuestionScenes");
                });

            modelBuilder.Entity("Jam.Api.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accessibility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dnf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("StoryId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Jam.Api.Models.AnswerOption", b =>
                {
                    b.HasOne("Jam.Api.Models.QuestionScene", "QuestionScene")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionSceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionScene");
                });

            modelBuilder.Entity("Jam.Api.Models.EndingScene", b =>
                {
                    b.HasOne("Jam.Api.Models.Story", "Story")
                        .WithMany("EndingScenes")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Jam.Api.Models.IntroScene", b =>
                {
                    b.HasOne("Jam.Api.Models.Story", "Story")
                        .WithOne("IntroScene")
                        .HasForeignKey("Jam.Api.Models.IntroScene", "StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Jam.Api.Models.PlayingSession", b =>
                {
                    b.HasOne("Jam.Api.Models.Story", "Story")
                        .WithMany("PlayingSessions")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Jam.Api.Models.QuestionScene", b =>
                {
                    b.HasOne("Jam.Api.Models.QuestionScene", "NextQuestionScene")
                        .WithMany()
                        .HasForeignKey("NextQuestionSceneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jam.Api.Models.Story", "Story")
                        .WithMany("QuestionScenes")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextQuestionScene");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Jam.Api.Models.QuestionScene", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("Jam.Api.Models.Story", b =>
                {
                    b.Navigation("EndingScenes");

                    b.Navigation("IntroScene")
                        .IsRequired();

                    b.Navigation("PlayingSessions");

                    b.Navigation("QuestionScenes");
                });
#pragma warning restore 612, 618
        }
    }
}
